name: 自動編譯 Windows 執行檔

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: 簽出程式碼
        uses: actions/checkout@v4

      - name: 設定 Node.js 環境
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: 安裝依賴
        run: npm install

      - name: 生成圖示
        run: npm run generate-icons

      - name: 編譯應用程式
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 上傳編譯結果
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/*.exe

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest

    steps:
      - name: 下載編譯結果
        uses: actions/download-artifact@v4
        with:
          name: windows-exe
          path: dist

      - name: 創建發布
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 